apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 598827825328.dkr.ecr.us-west-2.amazonaws.com/myapp:<version>
        ports:
        - containerPort: 8080
